name: say hello
on:
  push:
    branches:
      - main
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, World!"
      - name: dime la fecha
        run: date
      - run: esta es la fecha